# Generated by Django 3.2.7 on 2021-10-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaticWeapon',
            fields=[
                ('hash', models.PositiveBigIntegerField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('weapon_dict', models.JSONField(editable=False)),
            ],
        ),
    ]
