# Generated by Django 3.2.7 on 2022-03-03 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticweapon',
            name='current_watermark',
            field=models.CharField(default='watermark', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
