# Generated by Django 3.2.7 on 2022-03-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_staticweapon_current_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticweapon',
            name='original_watermark',
            field=models.CharField(default='origin', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
