# Generated by Django 3.2.7 on 2022-03-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_staticweapon_original_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticweapon',
            name='source_hash',
            field=models.PositiveBigIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staticweapon',
            name='source_string',
            field=models.CharField(default='n/a', editable=False, max_length=120),
            preserve_default=False,
        ),
    ]
