# Generated by Django 3.2.7 on 2022-03-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_staticweapon_origin_trait_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticweapon',
            name='relevent_original_watermark',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
