# Generated by Django 3.2.7 on 2022-03-09 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_staticweapon_relevent_original_watermark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staticweapon',
            old_name='relevent_original_watermark',
            new_name='original_nonsunset_watermark',
        ),
    ]
