# Generated by Django 3.2.7 on 2022-03-09 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_relevent_original_watermark_staticweapon_original_nonsunset_watermark'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticweapon',
            name='season_information',
            field=models.JSONField(default=[]),
            preserve_default=False,
        ),
    ]
