# Generated by Django 3.2.7 on 2024-02-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_staticweapon_season_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticweapon',
            name='current_watermark',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staticweapon',
            name='original_watermark',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
